dist: trusty
sudo: required
language: cpp

os:
  - linux

compiler:
  - gcc
  # TODO: - clang

sources: ['ubuntu-toolchain-r-test']
packages: ['g++-8']

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release CI_NAME=TRAVIS
  # TODO: - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  # build environment setup script
  - source build/travis-install-env-$TRAVIS_OS_NAME.sh

script:
  # Build project
  - mkdir -p build && cd build
  - conan install --build=missing ./conanfile.txt
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .

  # Run tests
  - ls CMakeFiles
  - ls .
  - ls ..
  - ls ../tests
  - ls ../tests/libfastsignals_unit_tests
  - ls ../..
  - ls ../../bin
  - ls ../../build
  - bin/libfastsignals_unit_tests
